version: '3.9'


services:
  coordinator:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: coordinator
    hostname: coordinator

  client-1:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    hostname: client-1
    depends_on:
      - coordinator

  client-2:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    hostname: client-2
    depends_on:
      - coordinator
